const $=id=>document.getElementById(id);
const subjects=['Matematik','Türk Dili ve Edebiyatı','Fizik','Kimya','Biyoloji','Tarih','Coğrafya','İngilizce','Din Kültürü ve Ahlak Bilgisi'];
const icons={'Matematik':'√x','Türk Dili ve Edebiyatı':'📖','Fizik':'⚛','Kimya':'⚗','Biyoloji':'🍃','Tarih':'🏛','Coğrafya':'🌍','İngilizce':'A↔','Din Kültürü ve Ahlak Bilgisi':'☾'};
const short={'Türk Dili ve Edebiyatı':'Türk Dili','Din Kültürü ve Ahlak Bilgisi':'Din Kültürü'};
const provinces=['Adana','Adıyaman','Afyonkarahisar','Ağrı','Aksaray','Amasya','Ankara','Antalya','Ardahan','Artvin','Aydın','Balıkesir','Bartın','Batman','Bayburt','Bilecik','Bingöl','Bitlis','Bolu','Burdur','Bursa','Çanakkale','Çankırı','Çorum','Denizli','Diyarbakır','Düzce','Edirne','Elazığ','Erzincan','Erzurum','Eskişehir','Gaziantep','Giresun','Gümüşhane','Hakkâri','Hatay','Iğdır','Isparta','İstanbul','İzmir','Kahramanmaraş','Karabük','Karaman','Kars','Kastamonu','Kayseri','Kırıkkale','Kırklareli','Kırşehir','Kilis','Kocaeli','Konya','Kütahya','Malatya','Manisa','Mardin','Mersin','Muğla','Muş','Nevşehir','Niğde','Ordu','Osmaniye','Rize','Sakarya','Samsun','Siirt','Sinop','Sivas','Şanlıurfa','Şırnak','Tekirdağ','Tokat','Trabzon','Tunceli','Uşak','Van','Yalova','Yozgat','Zonguldak'];

const Q=[
['Matematik','Kolay','√49 + |−3| işleminin sonucu kaçtır?',['4','7','10','52'],2,'√49=7 ve |−3|=3 olduğundan sonuç 10’dur.'],
['Matematik','Orta','2x−5=13 denkleminde x kaçtır?',['4','7','9','18'],2,'2x=18, buradan x=9.'],
['Matematik','Orta','200 TL olan ürün %20 zamlanırsa yeni fiyat kaç TL olur?',['220','230','240','250'],2,'200×1,20=240 TL.'],
['Matematik','Zor','|x−3|=5 eşitliğinin çözümleri hangileridir?',['8 ve −2','5 ve −5','3 ve 5','8 ve 2'],0,'x, 3 sayısından 5 birim uzaktadır: 8 veya −2.'],
['Matematik','Orta','Dik kenarları 6 ve 8 olan dik üçgenin hipotenüsü kaçtır?',['9','10','12','14'],1,'Pisagor: 6²+8²=100, hipotenüs 10.'],
['Türk Dili ve Edebiyatı','Kolay','Bir metinde doğrudan söylenmeyip çıkarımla ulaşılan anlama ne denir?',['Açık ileti','Örtük ileti','Başlık','Kafiye'],1,'Örtük ileti, metnin ipuçlarından çıkarılan anlamdır.'],
['Türk Dili ve Edebiyatı','Orta','“Akşam şehrin omuzlarına sessizlik bıraktı.” cümlesinde öne çıkan özellik hangisidir?',['Sayısal veri','İmgesel söyleyiş','Tanım','Nesnel açıklama'],1,'Şehrin omuzları ve sessizliğin bırakılması imgesel söyleyiş oluşturur.'],
['Türk Dili ve Edebiyatı','Kolay','Yazarın kişisel düşüncelerini samimi biçimde anlattığı tür hangisidir?',['Deneme','Tutanak','Haber','Dilekçe'],0,'Deneme kişisel düşüncelerin serbestçe işlendiği türdür.'],
['Türk Dili ve Edebiyatı','Orta','Bir kişiyle soru-cevap biçiminde yapılan görüşmenin yazıya aktarılması hangi türdür?',['Fabl','Mülakat','Masal','Destan'],1,'Soru-cevap temelli görüşme türü mülakattır.'],
['Türk Dili ve Edebiyatı','Zor','“Küçük ama sürekli gelişmeler zamanla büyük sonuç verir.” yargısının ana mesajı nedir?',['Hızlı sonuç şarttır','Süreklilik gelişimi büyütür','Değişim imkânsızdır','Büyük karar tek yoldur'],1,'Vurgu küçük fakat düzenli iyileştirmelerin birikimidir.'],
['Fizik','Kolay','Aşağıdakilerden hangisi vektörel bir büyüklüktür?',['Sürat','Enerji','Kuvvet','Sıcaklık'],2,'Kuvvet büyüklük ve yön bilgisine sahiptir.'],
['Fizik','Orta','150 metreyi 30 saniyede alan aracın ortalama sürati kaç m/s’dir?',['3','5','6','9'],1,'Sürat=yol/zaman=150/30=5 m/s.'],
['Fizik','Orta','Aynı sıvıda derinlik arttıkça sıvı basıncı nasıl değişir?',['Azalır','Değişmez','Artar','Sıfırlanır'],2,'Sıvı basıncı derinlikle artar.'],
['Fizik','Zor','2 kg kütleli cisim 3 m/s hızla gidiyor. Kinetik enerjisi kaç J’dir?',['3','6','9','18'],2,'Ek=1/2·m·v²=9 J.'],
['Kimya','Kolay','Atom numarası 13 olan nötr atomda kaç elektron vardır?',['10','12','13','26'],2,'Nötr atomda proton ve elektron sayıları eşittir.'],
['Kimya','Orta','Elektron dağılımı 2,8,1 olan atom kaçıncı periyottadır?',['1','2','3','4'],2,'Elektron bulunan üç katman olduğundan 3. periyottadır.'],
['Kimya','Orta','NaCl oluşurken temel olarak hangi olay gerçekleşir?',['Elektron ortaklaşması','Proton alışverişi','Elektron alışverişi','Nötron ortaklaşması'],2,'Na elektron verir, Cl elektron alır; iyonik yapı oluşur.'],
['Kimya','Zor','Aynı periyotta soldan sağa atom yarıçapı genel olarak nasıl değişir?',['Artar','Azalır','Değişmez','Önce artar'],1,'Etkin çekirdek çekimi arttığından yarıçap genel olarak azalır.'],
['Biyoloji','Kolay','Canlıların ortak özelliklerinden biri hangisidir?',['Hepsinin fotosentez yapması','Hücresel yapıya sahip olması','Hepsinin uçması','Hepsinin eşeysiz üremesi'],1,'Canlılar hücresel organizasyona sahiptir.'],
['Biyoloji','Orta','Enzimlerin büyük çoğunluğu hangi yapıya sahiptir?',['Protein','Nişasta','Yağ','Vitamin'],0,'Enzimlerin çoğu protein yapılı biyolojik katalizördür.'],
['Biyoloji','Orta','ATP üretiminde önemli görev alan ökaryot organel hangisidir?',['Ribozom','Mitokondri','Golgi','Lizozom'],1,'Hücresel solunumun önemli basamakları mitokondride gerçekleşir.'],
['Biyoloji','Zor','Maddenin çok yoğun ortamdan az yoğun ortama ATP harcamadan geçişine ne denir?',['Aktif taşıma','Endositoz','Difüzyon','Ekzositoz'],2,'Enerji harcanmadan yoğunluk farkıyla gerçekleşen geçiş difüzyondur.'],
['Tarih','Orta','Tarım Devrimi’nin önemli sonuçlarından biri hangisidir?',['Yerleşik yaşamın yaygınlaşması','Yazının terk edilmesi','Ticaretin bitmesi','Şehirlerin yok olması'],0,'Tarım kalıcı yerleşmeleri desteklemiştir.'],
['Tarih','Orta','Olayın yaşandığı döneme ait bir yazıt hangi tür kaynaktır?',['Birinci el kaynak','İkinci el kaynak','Kurgu','Yorum'],0,'Döneme ait doğrudan belge ve buluntular birinci el kaynaktır.'],
['Coğrafya','Orta','CBS’nin önemli avantajlarından biri hangisidir?',['Yalnız metin yazması','Mekânsal verileri katmanlar hâlinde analiz etmesi','Sadece sıcaklık ölçmesi','Ölçeği kaldırması'],1,'CBS farklı mekânsal veri katmanlarını birlikte analiz eder.'],
['Coğrafya','Zor','Büyük ölçekli harita için hangisi doğrudur?',['Daha az ayrıntı','Daha fazla ayrıntı','Daima daha geniş alan','Ölçüm yapılamaz'],1,'Büyük ölçek dar alanı daha ayrıntılı gösterir.'],
['İngilizce','Kolay','Choose the correct answer: “Where are you from?”',['I am from Türkiye.','I can fifteen.','She are Turkish.','Yes, I from.'],0,'The question asks about country of origin.'],
['İngilizce','Orta','Choose the correct sentence about ability.',['She can speaks English.','She can speak English.','She can to speak English.','She cans speak English.'],1,'After “can”, use the base form of the verb.'],
['Din Kültürü ve Ahlak Bilgisi','Kolay','Hangisi İslam’ın iman esaslarından biri değildir?',['Allah’a iman','Meleklere iman','Ahirete iman','Zekât vermek'],3,'Zekât ibadettir; iman esaslarından biri değildir.'],
['Din Kültürü ve Ahlak Bilgisi','Orta','Allah ile iletişimin temel yolları arasında hangisi vurgulanır?',['İbadet ve dua','Ticaret ve seyahat','Spor ve yarışma','Teknoloji ve üretim'],0,'İbadet ve dua Allah-insan ilişkisinin temel boyutlarındandır.']
].map((x,i)=>({id:i,subject:x[0],difficulty:x[1],q:x[2],o:x[3],a:x[4],exp:x[5]}));

const notes={
'Matematik':[
['Mutlak Değer = Uzaklık','Mutlak değer sayı doğrusunda sıfıra olan uzaklıktır ve negatif olamaz.','|x−a|, x ile a arasındaki uzaklığı gösterir.','|x−3|=5 ise x=8 veya x=−2.','x<0 iken |x|=−x olur.'],
['Yüzde Değişimi','Ardışık artış ve azalışlar aynı tabandan yapılmaz.','Yeni değer = Eski değer × (1±oran).','200 TL %20 artıp %20 azalırsa 192 TL olur.','%20 artış ile %20 azalış birbirini götürmez.']],
'Türk Dili ve Edebiyatı':[
['Açık ve Örtük İleti','Açık ileti doğrudan, örtük ileti çıkarımla anlaşılır.','Örtük anlam metnin ipuçlarına dayanır.','“Ali yine geç kaldı.” daha önce de geç kaldığını düşündürür.','Metnin desteklemediği kişisel yorumu cevap gibi verme.'],
['Anlatıcı ve Yazar','Anlatıcı metindeki sestir, yazar gerçek kişidir.','Kahraman anlatıcı birinci kişi olabilir.','“O sabah istasyona erken geldim.” birinci kişi anlatıma örnektir.','Anlatıcıyı kanıtsız biçimde yazarla özdeşleştirme.']],
'Fizik':[
['Skaler ve Vektörel','Bazı büyüklüklerde yön bilgisi gerekir.','Sürat skaler, hız ve kuvvet vektöreldir.','“60 km/sa doğuya” hız bilgisidir.','Sürat ile hızı fizik sorularında aynı kabul etme.'],
['Katı Basıncı','Aynı kuvvet daha küçük alanda daha büyük basınç oluşturur.','P=F/A.','İnce topuk zemine daha büyük basınç uygular.','Basınç ile basınç kuvvetini karıştırma.']],
'Kimya':[
['Atomun Parçacıkları','Çekirdekte proton ve nötron, çevrede elektron bulunur.','Atom numarası proton sayısıdır.','Atom numarası 8 ise proton sayısı 8’dir.','Nötr atomda proton=elektron; iyonda değişebilir.'],
['İyonik ve Kovalent','Bağ oluşumunda elektron alışverişi veya ortaklaşması olabilir.','NaCl iyonik, H₂O’daki O–H bağları kovalenttir.','Na elektron verir, Cl alır.','Bağ türünü yalnız formül görünüşüne göre seçme.']],
'Biyoloji':[
['Prokaryot ve Ökaryot','Prokaryotlarda zarla çevrili çekirdek yoktur.','Bakteriler prokaryot; bitki ve hayvan hücreleri ökaryottur.','Bakteri DNA taşır ama çekirdeği yoktur.','“Çekirdeksiz” ifadesini “DNA’sız” sanma.'],
['Metabolizma','Yapım ve yıkım olaylarının tümü metabolizmadır.','Anabolizma yapım, katabolizma yıkımdır.','Protein sentezi anabolik bir olaydır.','Her metabolik olay yalnız enerji üretmek için değildir.']],
'Tarih':[
['Birinci El Kaynak','Olay döneminden kalan doğrudan belge ve nesneler önemlidir.','Dönem yazıtı birinci el kaynaktır.','Antlaşmanın özgün metni birinci el kaynaktır.','Birinci el kaynak da taraflı olabilir; sorgula.'],
['Anakronizm','Geçmişe ait olmayan kavramı geçmişe taşımak tarihsel hatadır.','Anakronizm zaman uyumsuzluğudur.','Antik Çağ olayını sosyal medya kavramıyla birebir açıklamak sorunlu olabilir.','Geçmişi yalnız bugünün değerleriyle yargılama.']],
'Coğrafya':[
['Harita Ölçeği','Büyük ölçek daha küçük alanı daha ayrıntılı gösterir.','1/25.000, 1/1.000.000’dan daha büyük ölçektir.','Payda küçüldükçe ölçek büyür.','Paydanın büyümesini ölçeğin büyümesi sanma.'],
['Hava Durumu ve İklim','Hava kısa süreli, iklim uzun yılların genel özelliğidir.','“Bugün yağmurlu” hava durumudur.','“Akdeniz yazları sıcak ve kuraktır.” iklim ifadesidir.','Tek günlük olaydan iklim sonucu çıkarma.']],
'İngilizce':[
['Simple Present / Continuous','Simple Present rutin; Present Continuous şu anda süren işler için kullanılır.','I study every day / I am studying now.','Today she is taking the bus.','“Now” çoğu zaman continuous için ipucudur.'],
['Frequency Adverbs','Always, usually, often, sometimes, never sıklık bildirir.','Ana fiilden önce, be fiilinden sonra gelir.','I often read. / She is always punctual.','Never zaten olumsuzdur; ayrıca don’t ekleme.']],
'Din Kültürü ve Ahlak Bilgisi':[
['İman Esasları','İman esasları bir bütün olarak değerlendirilir.','Allah, melek, kitap, peygamber, ahiret ve kadere iman temel başlıklardır.','Peygamberlere iman rehberlik için elçiler gönderildiğini kabul eder.','İman esaslarını kopuk ezberler olarak görme.'],
['Ahlaki İlkeler','Doğruluk, adalet, sorumluluk ve merhamet toplumsal hayatı güçlendirir.','Ahlaki ilke davranışa yön veren ölçüttür.','Kimse görmese de kopya çekmemek doğrulukla ilgilidir.','Ahlakı yalnız başkalarının yanında sergilenen davranış sanma.']]
};

const openMath=['f(x)=x²−4x+3 fonksiyonunun köklerini bulunuz. İşlem basamaklarınızı gösteriniz.','Bir ürünün fiyatı önce %20 artırılıp sonra yeni fiyat üzerinden %20 azaltılıyor. Son fiyatın ilk fiyata göre değişimini gerekçeli bulunuz.','|2x−5|≤7 eşitsizliğinin çözüm kümesini sayı doğrusunda göstererek yazınız.','Dik kenarları 6 cm ve 8 cm olan dik üçgende hipotenüsü bulunuz ve kullandığınız ilişkiyi açıklayınız.','Ardışık üç tek sayının toplamı 63’tür. Sayıları denklem kurarak bulunuz.','Bir doğru parçası 2:3 oranında bölünüyor. Parçaların farkı 7 cm ise tamamını bulunuz.','A={1,2,3,4,5}, B={2,4,6} için A∩B ve A∪B kümelerini yazınız.'];
const openLit=['“İnsan bazen en uzun yolu kendi içinde yürür.” cümlesinin çağrıştırdığı düşünceyi gerekçeli açıklayınız.','Bir öyküde anlatıcı ile yazarın neden aynı kabul edilemeyeceğini örnekleyiniz.','“Rüzgâr pencerelere eski bir masalı fısıldadı.” cümlesindeki söz sanatını açıklayınız.','Ana düşünceyi belirlerken yararlandığınız en az iki ölçütü yazınız.','“Kitap okumak insanı değiştirir.” yargısını destekleyen 4–5 cümlelik paragraf yazınız.','Şiir ile düzyazı arasındaki iki temel farkı açıklayınız.','Açık ileti ile örtük ileti arasındaki farkı açıklayıp örnek veriniz.'];

let state=JSON.parse(localStorage.getItem('arena9-github')||'null')||{name:'Arena Öğrencisi',province:'İstanbul',xp:0,solved:[],correct:0,wrong:0,streak:1,subject:{},noteRead:[],best:null};
let view='home',order=Q.map(q=>q.id),pos=0,answered=false,mode='study',examAns=Array(Q.length).fill(null),examSec=2700,examInt=null;
let noteSubject=null,notePos=0,openType=null,openPos=0,openAnswers=[],openSec=2400,openInt=null;
function save(){let current={};try{current=JSON.parse(localStorage.getItem('arena9-github')||'{}')||{}}catch(e){}localStorage.setItem('arena9-github',JSON.stringify(Object.assign(current,state)))}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('show'),1700)}
function countdown(){let ms=Math.max(0,new Date('2027-06-25T00:00:00+03:00')-new Date());$('d').textContent=Math.floor(ms/86400000);$('h').textContent=String(Math.floor(ms%86400000/3600000)).padStart(2,'0');$('m').textContent=String(Math.floor(ms%3600000/60000)).padStart(2,'0');$('s').textContent=String(Math.floor(ms%60000/1000)).padStart(2,'0')}
function rank(){let n=state.solved.length,a=(state.correct+state.wrong)?state.correct/(state.correct+state.wrong):0,tr=Math.max(1,48217-n*173-Math.round(a*4300));return{tr,city:Math.max(1,Math.round(tr/34)+Math.max(0,85-n*3)),acc:Math.round(a*100)}}
function go(v){view=v;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}
function openProfile(t){go('profile');switchTab(t)}
function switchTab(t){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));document.querySelectorAll('.pane').forEach(p=>p.classList.remove('active'));$('pane-'+t).classList.add('active')}
function render(){let r=rank(),n=state.solved.length,l=Math.floor(state.xp/500)+1;$('xpTop').textContent=state.xp+' XP';$('level').textContent=l;$('xpText').textContent=(state.xp%500)+'/500';$('xpBar').style.width=(state.xp%500/5)+'%';$('solvedHome').textContent=n+' benzersiz soru';$('rankHome').textContent='TR #'+r.tr.toLocaleString('tr-TR')+' • İL #'+r.city.toLocaleString('tr-TR');$('provinceHome').textContent=state.province;$('coachHome').textContent=n<10?'Bugün 20 soru hedefiyle başla. İlk görev Matematik.':r.acc<65?'Yanlışlarının yoğunlaştığı dersi güçlendirelim.':'Ritmin iyi. Açık uçlu ortak sınav provası ekleyelim.';$('goalPill').textContent='🎯 '+Math.min(20,n%21)+'/20';$('streakPill').textContent='🔥 '+state.streak+' gün';$('profileName').textContent=state.name;$('nameInput').value=state.name;$('provinceSelect').value=state.province;$('trRank').textContent='#'+r.tr.toLocaleString('tr-TR');$('cityRank').textContent='#'+r.city.toLocaleString('tr-TR');$('cityLabel').textContent=state.province.toUpperCase();$('trMeta').textContent=n+' soru • %'+r.acc+' doğruluk';$('cityMeta').textContent=state.province+' • %'+r.acc;$('myRank').textContent='#'+r.tr.toLocaleString('tr-TR');$('myName').textContent=state.name;$('mySolved').textContent=n+' soru';$('rSolved').textContent=n;$('rAccuracy').textContent='%'+r.acc;$('rXp').textContent=state.xp;let best=$('bestScore');if(best)best.textContent=state.best===null?'—':state.best;buildLessons();buildBars();weakTask()}
function buildLessons(){$('lessonGrid').innerHTML=subjects.map(s=>{let v=state.subject[s]||{c:0,t:0},p=v.t?Math.round(v.c/v.t*100):0,read=state.noteRead.filter(x=>x.startsWith(s+'|')).length,total=notes[s].length;return `<button class="lesson" onclick='startSubject(${JSON.stringify(s)})'><span class="note-badge" onclick='event.stopPropagation();openNotes(${JSON.stringify(s)})'>🧠 ${read}/${total}</span><i>${icons[s]}</i><b>${short[s]||s}</b><small>${v.t?v.t+' soru • %'+p:'Soru çöz'} • Notlar</small></button>`}).join('')}
function buildBars(){let a=subjects.map(s=>{let v=state.subject[s]||{c:0,t:0};return[s,v.t?Math.round(v.c/v.t*100):0,v.t]}).sort((a,b)=>b[2]-a[2]).slice(0,5);$('bars').innerHTML='<h4>DERS BAZLI BAŞARI</h4>'+a.map(x=>`<div class="bar-row"><b>${short[x[0]]||x[0]}</b><div class="progress"><i style="width:${x[1]}%"></i></div><span>%${x[1]}</span></div>`).join('')}
function weakTask(){let w='Fizik',min=2;subjects.forEach(s=>{let v=state.subject[s];if(v&&v.t&&v.c/v.t<min){min=v.c/v.t;w=s}});$('weakTitle').textContent=(short[w]||w)+' • 5 soru';$('weakSub').textContent=min===2?'Zayıf konu takviyesi':'Son başarı %'+Math.round(min*100);$('weakTask').onclick=()=>startSubject(w)}
function startStudy(){mode='study';order=Q.map(q=>q.id);pos=0;openQuestion()}
function startSubject(s){mode='study';order=Q.filter(q=>q.subject===s).map(q=>q.id);pos=0;openQuestion()}
function openQuestion(){$('questionOverlay').classList.add('show');drawQ()}
function closeQuestion(){$('questionOverlay').classList.remove('show');render()}
function drawQ(){let q=Q[order[pos]];$('qSubject').textContent=short[q.subject]||q.subject;$('qDifficulty').textContent=q.difficulty;$('qProgress').style.width=((pos+1)/order.length*100)+'%';$('qCounter').textContent=(pos+1)+'/'+order.length+'  ×';$('qCounter').onclick=closeQuestion;$('qCounter').title='Kapat';$('qMode').textContent=mode==='exam'?'ARENA DENEME 01':'SERBEST ÇALIŞMA';$('qTimer').textContent=mode==='exam'?fmt(examSec):'Süresiz';$('qText').textContent=q.q;$('options').innerHTML=q.o.map((o,i)=>`<button class="option" onclick="answerQ(${i})"><i>${'ABCD'[i]}</i><span>${o}</span></button>`).join('');answered=false;$('nextQuestion').textContent=pos===order.length-1?(mode==='exam'?'DENEMEYİ BİTİR':'KAPAT'):'Sonraki →';if(mode==='exam'&&examAns[q.id]!==null){[...$('options').children].forEach((b,i)=>b.classList.toggle('selected',i===examAns[q.id]));answered=true}}
function answerQ(c){let q=Q[order[pos]],os=[...$('options').children];if(mode==='exam'){examAns[q.id]=c;os.forEach((b,i)=>b.classList.toggle('selected',i===c));answered=true;return}if(answered)return;answered=true;let ok=c===q.a;os.forEach((b,i)=>{if(i===q.a)b.classList.add('correct');else if(i===c)b.classList.add('wrong')});if(!state.solved.includes(q.id)){state.solved.push(q.id);state[ok?'correct':'wrong']++;state.xp+=ok?25:10;state.subject[q.subject]=state.subject[q.subject]||{c:0,t:0};state.subject[q.subject].t++;if(ok)state.subject[q.subject].c++;save();render()}toast(ok?'Doğru cevap • +25 XP':'Yanlış • çözüm yolunu incele')}
function nextQ(){if(pos<order.length-1){pos++;drawQ()}else if(mode==='exam'){finishExam()}else closeQuestion()}
function info(k,t,p,b){$('infoKicker').textContent=k;$('infoTitle').textContent=t;$('infoText').textContent=p;$('infoBox').textContent=b;$('infoOverlay').classList.add('show')}
function closeInfo(){$('infoOverlay').classList.remove('show')}
function hint(){let q=Q[order[pos]];info('💡 ZEUS İPUCU','İpucu','Cevabı doğrudan vermeden ilk adım:',q.exp.split(/[.;]/)[0]+'.')}
function solution(){let q=Q[order[pos]];info('⚡ ÇÖZÜM YOLU','Adım Adım Çözüm','Bu soruda kullanman gereken temel yaklaşım:',q.exp)}
function startExam(){mode='exam';order=Q.map(q=>q.id);pos=0;examAns=Array(Q.length).fill(null);examSec=2700;clearInterval(examInt);examInt=setInterval(()=>{examSec--;if($('questionOverlay').classList.contains('show'))$('qTimer').textContent=fmt(examSec);if(examSec<=0){clearInterval(examInt);finishExam()}},1000);openQuestion();toast('45 dakikalık Arena Deneme 01 başladı')}
function finishExam(){clearInterval(examInt);let c=0,w=0,e=0;Q.forEach(q=>{let a=examAns[q.id];if(a===null){e++;return}let ok=a===q.a;ok?c++:w++;if(!state.solved.includes(q.id)){state.solved.push(q.id);state[ok?'correct':'wrong']++;state.xp+=ok?25:10;state.subject[q.subject]=state.subject[q.subject]||{c:0,t:0};state.subject[q.subject].t++;if(ok)state.subject[q.subject].c++}});let sc=Math.round(c/Q.length*100);state.best=state.best===null?sc:Math.max(state.best,sc);save();mode='study';closeQuestion();go('exams');info('🏆 ARENA DENEME 01','Deneme Sonucun',c+' doğru • '+w+' yanlış • '+e+' boş',sc+'/100 puan. Türkiye ve il sıralaman çözülen benzersiz sorulara göre güncellendi.')}
function openNotes(s){noteSubject=s;notePos=0;$('notesOverlay').classList.add('show');drawNote()}
function drawNote(){let a=notes[noteSubject],n=a[notePos],key=noteSubject+'|'+notePos;if(!state.noteRead.includes(key)){state.noteRead.push(key);state.xp+=2;save()}$('noteSubject').textContent=short[noteSubject]||noteSubject;$('noteCounter').textContent=(notePos+1)+'/'+a.length;$('noteTitle').textContent=n[0];$('noteInfo').textContent=n[1];$('noteConcept').textContent=n[2];$('noteExample').textContent=n[3];$('noteCaution').textContent=n[4];$('noteNext').textContent=notePos===a.length-1?'SORU ÇÖZ →':'Sonraki →';render()}
function notePrev(){if(notePos>0){notePos--;drawNote()}else toast('İlk Akıllı Not kartındasın')}
function noteNext(){if(notePos<notes[noteSubject].length-1){notePos++;drawNote()}else{closeNotes();startSubject(noteSubject)}}
function closeNotes(){$('notesOverlay').classList.remove('show');render()}
function coachTool(t){let d={program:['📅 ZEUS PROGRAMI','Bugünün Planı','10 Matematik + 5 Türk Dili + zayıf olduğun dersten 5 soru. Ardından kısa yanlış analizi.'],strategy:['🎯 SINAV STRATEJİSİ','Arena Stratejisi','Önce emin olduğun soruları çöz. 90 saniyeyi aşan soruyu işaretleyip ilerle. Son turu kontrole ayır.'],motivation:['⚡ ZEUS','Günün Mesajı','Hedef bir günde tamamlanan büyük iş değil, her gün yeniden kurulan düzenin sonucudur.']}[t];info(d[0],d[1],'Zeus Koçluğu önerisi:',d[2])}
function startOpen(t){openType=t;openPos=0;openAnswers=Array(7).fill('');openSec=2400;$('openOverlay').classList.add('show');drawOpen();clearInterval(openInt);openInt=setInterval(()=>{openSec--;$('openTimer').textContent=fmt(openSec);if(openSec<=0){clearInterval(openInt);finishOpen()}},1000)}
function openQs(){return openType==='math'?openMath:openLit}
function drawOpen(){$('openTitle').textContent=openType==='math'?'MATEMATİK • AÇIK UÇLU':'TÜRK DİLİ VE EDEBİYATI • AÇIK UÇLU';$('openQuestion').textContent=(openPos+1)+'. '+openQs()[openPos];$('openAnswer').value=openAnswers[openPos]||'';$('openProgress').style.width=((openPos+1)/7*100)+'%';$('openNext').textContent=openPos===6?'SINAVI BİTİR':'Sonraki →';$('openTimer').textContent=fmt(openSec)}
function saveOpen(){openAnswers[openPos]=$('openAnswer').value}
function openPrev(){saveOpen();if(openPos>0){openPos--;drawOpen()}}
function openNext(){saveOpen();if(openPos<6){openPos++;drawOpen()}else finishOpen()}
function rubric(){info('📋 PUANLAMA','Açık Uçlu Değerlendirme','Demo rubriği:',openType==='math'?'Sonuç kadar işlem basamakları, kullanılan yöntem ve gerekçe değerlendirilir. Kısmi doğru işlemler kısmi puan alabilir.':'Ana düşünceyi yakalama, metne dayalı gerekçe, açıklık ve anlatım bütünlüğü birlikte değerlendirilir.')}
function finishOpen(){saveOpen();clearInterval(openInt);let n=openAnswers.filter(x=>x.trim().length>=8).length,sc=Math.round(n/7*100);state.xp+=n*15;save();$('openOverlay').classList.remove('show');render();info('📝 ORTAK SINAV','Deneme Tamamlandı',n+'/7 soruya yeterli uzunlukta cevap yazdın.','Demo katılım puanı: '+sc+'/100. Gerçek sürümde rubrik tabanlı kısmi puanlama ve öğretmen/AI değerlendirmesi bağlanacak.')}
function saveSettings(){state.name=$('nameInput').value.trim()||'Arena Öğrencisi';state.province=$('provinceSelect').value;save();render();toast('Profil güncellendi')}
function populate(){let html=provinces.map(p=>`<option ${p===state.province?'selected':''}>${p}</option>`).join('');$('provinceSelect').innerHTML=html}
populate();countdown();setInterval(countdown,1000);render();
